// New dashboard-orientation lessons, not a statement of deployed trading policy.
window.CST_ORIENTATION={lessons:[
 {n:1,title:'Find your way around',html:'<p>Use the numbered section links at the top. Start with Status, then Market setup, Positions and System details. Plain view hides Indicators and System; Detailed reveals them.</p><p>Read the account and environment before interpreting any figures. The page is read-only; the phone remains the decision surface.</p>'},
 {n:2,title:'A setup is not a trade',html:'<p>The signal ring counts three strategy conditions. A 3/3 means the displayed conditions were met, not a guaranteed win or permission to buy.</p><p>A proposal records intended terms. Approval records a decision. Submission sends an order. Only broker execution evidence establishes a fill.</p>'},
 {n:3,title:'Read a proposal before deciding',html:'<p>Match the account, symbol, side, quantity, entry limit, stop, target, estimated risk and expiry. Check the intended strategy and current positions.</p><p>Use the existing phone approval workflow only when the request is current and understood. This dashboard has no approval buttons. Declining is a valid decision.</p>'},
 {n:4,title:'Waiting orders and partial fills',html:'<p>A resting order has not necessarily filled. A partial fill opens only the executed quantity while the remaining order may still be working.</p><p>Compare the broker order and execution records with the Engine log. If they disagree, pause and investigate. Never resubmit simply because a run failed or a notification is missing.</p>'},
 {n:5,title:'Read risk without false certainty',html:'<p>The Risk at stops card is a limited estimate for displayed long stock positions with stop data. It is not a guaranteed maximum loss, and it does not establish total options or pending-order risk.</p><p>A stop may execute at a worse price. Missing evidence is not zero risk. Current approved policy, not a training example or your conviction, governs the allowed size.</p>'},
 {n:6,title:'Separate planning from trading',html:'<p>The gold card illustrates compounding from displayed paper equity. Changing a slider does not transfer money or schedule a contribution.</p><p>It is not your Fidelity Foundation account and does not combine Fidelity, TradeStation or IRA balances. Your investment plan remains separate from this paper display.</p>'},
 {n:7,title:'Understand freshness and system status',html:'<p>A recent page refresh does not prove the engine ran recently. Compare the System card’s last scan, state publication and verification timestamps.</p><p>If Today and the last-scan verdict disagree, do not pick whichever looks more encouraging. Confirm the current proposal and broker state before acting.</p>'},
 {n:8,title:'Finish with a useful review',html:'<p>Record the setup, intended terms, decision, broker outcome and what you learned. Review open positions and outstanding orders before ending your session.</p><p>This dashboard has no trade-journal editor. Existing lesson checkmarks are saved only in your browser when storage is available; they do not certify trading readiness.</p>'}
],glossary:{}};
